### ISSUE TITLE
Drag&drop-ondersteuning

### ISSUE THREAD

**Issue by radwouters** [collecthor/collecthor-file-browser#20]
Kleine QoL-upgrade, maar opzich wel nice: Drag&drop mogelijk maken. Zijn volgens mij zelfs libraries voor.

**Comment by SamMousa** [comment]
Hoe bedoel je drag & drop? Je kunt als het goed is al files droppen voor upload.
Waar wil je nog meer naar d&den?

**Comment by radwouters** [comment]
Ja, zie nu ook dat deze werkt schijnbaar. Ik heb een paar keer gehad dat hij niet werkte, maar dat zal wel aan mij of mijn machine gelegen hebben.
